name: Compila il libro
on:
  push:
    tags:
      - "libro-*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Install Liberation Mono font
        run: apt install fonts-liberation
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: GitHub Action for LaTeX
        uses: xu-cheng/latex-action@4.0.0
        with:
          root_file: "libro-linguaggi.tex"
          continue_on_error: true
          pre_compile: "cd img && latexmk *.tex && cd .."
          latexmk_use_lualatex: true      
      - name: Release PDF file
        uses: softprops/action-gh-release@v2
        with:
          files: "libro-linguaggi.pdf"

